#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "usage: $0 bitsy_path" >&2
  echo "       run all specs using bitsy implementation at bitsy_path" >&2
  exit 1
fi

SPECSUB=specs
BINSUB=bin
BINNAME=bitsyspec
BUILDSCRIPT=build.sh

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
SPECPATH=$SCRIPTPATH/$SPECSUB
BINPATH=$SCRIPTPATH/$BINSUB/$BINNAME
BUILDPATH=$SCRIPTPATH/$BUILDSCRIPT

if [ ! -f "$BINPATH" ]; then
  CURDIR="$(pwd -P)"
  cd $SCRIPTPATH; $BUILDPATH
  cd $CURDIR
fi

$BINPATH $1 $SPECPATH
